name: Linting

on:
  pull_request:
    branches: [ v1.* ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run checkstyle in source code
        run: ./gradlew checkstyleMain

      - name: Run checkstyle in test code
        run: ./gradlew checkstyleTest
