name: Publish

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build -x test --refresh-dependencies

      - name: Run unit tests
        run: ./gradlew test

      - name: Publish
        if: ${{ github.ref_type == 'tag' }}
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache -Pmockbukkit.version=$(echo ${{ github.ref_name }} | sed -e 's:v::')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.KEY_PASS }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PRIV_KEY }}
